### ISSUE TITLE
error: Accessing "__init__" on an instance is unsound, since instance.__init__ could be from an incompatible subclass

### ISSUE THREAD

**Issue by pjonsson** [opendatacube/odc-geo#228]
I added a couple of type ignores in #227, but this should probably be fixed:
```
odc/geo/crs.py:126: error: Accessing "__init__" on an instance is unsound, since instance.__init__ could be from an incompatible subclass  [misc]
odc/geo/geom.py:940: error: Accessing "__init__" on an instance is unsound, since instance.__init__ could be from an incompatible subclass  [misc]
```

**Comment by Kirill888** [comment]
fixed by #227

**Comment by pjonsson** [comment]
@Kirill888 that solved half of it, issue still exists in `geom.py:940` on latest develop, so I'll reopen this.
